package io.codemodder;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Used by {@link CodemodProvider}s for requesting {@link RuleSarif}s generated by a given list of
 * tools.
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface WantsSarif {

  /** A list of all the tool names. */
  String[] toolNames();
}
