package io.codemodder.providers.sarif.semgrep;

import com.contrastsecurity.sarif.Result;
import com.github.javaparser.ast.Node;
import io.codemodder.CodemodReporterStrategy;
import io.codemodder.FixOnlyCodeChanger;
import io.codemodder.RegionNodeMatcher;
import io.codemodder.RuleSarif;
import io.codemodder.SarifPluginJavaParserChanger;
import io.codemodder.SourceCodeRegionExtractor;

/**
 * Provides foundational functionality for modifying Java code using JavaParser based on findings
 * from a SARIF file generated by Semgrep analysis. This class implements {@link
 * FixOnlyCodeChanger}, signifying its role as a code transformation tool that exclusively addresses
 * identified issues without conducting independent detection, leveraging results from Semgrep
 * analysis.
 */
public abstract class SemgrepSarifJavaParserChanger<T extends Node>
    extends SarifPluginJavaParserChanger<T> implements FixOnlyCodeChanger {

  protected SemgrepSarifJavaParserChanger(
      final RuleSarif sarif, final Class<? extends Node> nodeType) {
    super(sarif, nodeType);
  }

  protected SemgrepSarifJavaParserChanger(
      final RuleSarif sarif,
      final Class<? extends Node> nodeType,
      final SourceCodeRegionExtractor<Result> regionExtractor) {
    super(sarif, nodeType, regionExtractor);
  }

  protected SemgrepSarifJavaParserChanger(
      final RuleSarif sarif,
      final Class<? extends Node> nodeType,
      final CodemodReporterStrategy codemodReporterStrategy) {
    super(sarif, nodeType, codemodReporterStrategy);
  }

  protected SemgrepSarifJavaParserChanger(
      final RuleSarif sarif,
      final Class<? extends Node> nodeType,
      final RegionNodeMatcher regionNodeMatcher) {
    super(sarif, nodeType, regionNodeMatcher);
  }

  protected SemgrepSarifJavaParserChanger(
      final RuleSarif sarif,
      final Class<? extends Node> nodeType,
      final RegionNodeMatcher regionNodeMatcher,
      final CodemodReporterStrategy reporterStrategy) {
    super(sarif, nodeType, regionNodeMatcher, reporterStrategy);
  }

  protected SemgrepSarifJavaParserChanger(
      final RuleSarif sarif,
      final Class<? extends Node> nodeType,
      final SourceCodeRegionExtractor<Result> regionExtractor,
      final RegionNodeMatcher regionNodeMatcher) {
    super(sarif, nodeType, regionExtractor, regionNodeMatcher);
  }

  protected SemgrepSarifJavaParserChanger(
      final RuleSarif sarif,
      final Class<? extends Node> nodeType,
      final SourceCodeRegionExtractor<Result> regionExtractor,
      final RegionNodeMatcher regionNodeMatcher,
      final CodemodReporterStrategy reporter) {
    super(sarif, nodeType, regionExtractor, regionNodeMatcher, reporter);
  }

  @Override
  public String vendorName() {
    return "Semgrep";
  }
}
