package io.codemodder.providers.sarif.codeql;

import com.contrastsecurity.sarif.Result;
import com.github.javaparser.ast.Node;
import io.codemodder.RuleSarif;
import io.codemodder.SarifPluginFixOnlyCodeChanger;
import io.codemodder.SourceCodeRegionExtractor;

/**
 * Provides foundational functionality for modifying Java code using JavaParser based on findings
 * from a SARIF file generated by Semgrep analysis.
 */
public abstract class CodeQLSarifJavaParserChanger<T extends Node>
    extends SarifPluginFixOnlyCodeChanger<T> {
  public CodeQLSarifJavaParserChanger(
      final RuleSarif sarif,
      final Class<? extends Node> nodeType,
      final SourceCodeRegionExtractor<Result> regionExtractor) {
    super(sarif, nodeType, regionExtractor);
  }

  @Override
  public String vendorName() {
    return "CodeQL";
  }
}
