name: Base Container Image

env:
  AWS_REGION: "us-east-1"

on:
  workflow_dispatch:

jobs:
  push:
    name: Build & Push Base Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Fetch AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::218200003247:role/DeployCodemodderImagesRole
          role-session-name: github
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Base Image
        run: |
          docker buildx build --push -t ${{ steps.login-ecr.outputs.registry }}/pixee/codemodder-java:base-image .
        working-directory: base-image
